[project]
name = "sketchstudio-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "numpy>=2.5.3",
    "opencv-python-headless>=5.0.0.93",
    "pillow>=12.3.0",
    "pydantic>=2.13.5",
    "python-multipart>=0.0.32",
    "reportlab>=5.0.1",
    "uvicorn>=0.52.4",
]
