import type { ProjectState } from '../types/studio';
import { generateDefaultLayerMeta } from './pencilGrades';
import { generateDefaultCutPoints } from './cutPoints';
import { DEFAULT_VALUE_FAMILY_FLOORS } from './tonalDecision';
import { CONSTRUCTION_INK, TRANSFER_GRID_INK } from './inkColors';
import { createInitialEdgeQualityState } from './edgeQuality';

export const INITIAL_PROJECT_STATE: ProjectState = {
  title: 'Classical Portrait Study',
  imageSrc: null,
  imageWidth: 600,
  imageHeight: 800,
  medium: 'graphite',
  stage: 1,
  isSandbox: false,
  numValueLayers: 5,
  layerMeta: generateDefaultLayerMeta(5),
  cutPoints: generateDefaultCutPoints(5),
  grid: {
    enabled: true,
    type: 'squares',
    cellSizeMm: 15,
    lineColor: TRANSFER_GRID_INK,
    lineWidth: 1,
    opacity: 0.75,
    showLabels: true,
    showSubdivisions: false,
    subdivisions: 2,
    showDiagonalsInCells: false,
    dotRadius: 2,
  },
  calibration: {
    isCalibrated: false,
    screenDpi: 96,
    pixelsPerMm: 3.78,
  },
  paperMapping: {
    isDeclared: false,
    paperPreset: 'A4',
    paperWidthMm: 210,
    paperHeightMm: 297,
    fillMode: 'fillWidth',
  },
  methods: {
    activeMethod: 'loomis',
    opacity: 0.85,
    color: CONSTRUCTION_INK,
    showAnchorPoints: true,
    loomis: {
      center: { x: 300, y: 340 },
      radius: 170,
      browLineY: 340,
      noseLineY: 440,
      chinY: 550,
      jawWidth: 150,
      tiltAngle: 0,
    },
    reilly: {
      browCenter: { x: 300, y: 330 },
      noseTip: { x: 300, y: 440 },
      mouthCenter: { x: 300, y: 500 },
      chinBottom: { x: 300, y: 550 },
      leftEye: { x: 235, y: 345 },
      rightEye: { x: 365, y: 345 },
      leftJaw: { x: 190, y: 460 },
      rightJaw: { x: 410, y: 460 },
      leftTemple: { x: 180, y: 280 },
      rightTemple: { x: 420, y: 280 },
    },
    bargue: {
      points: [
        { id: 'p1', x: 300, y: 140 },
        { id: 'p2', x: 450, y: 280 },
        { id: 'p3', x: 430, y: 500 },
        { id: 'p4', x: 350, y: 600 },
        { id: 'p5', x: 250, y: 600 },
        { id: 'p6', x: 170, y: 500 },
        { id: 'p7', x: 150, y: 280 },
      ],
      plumbLines: [{ x: 235 }, { x: 300 }, { x: 365 }],
      levelBars: [{ y: 345 }, { y: 440 }, { y: 500 }, { y: 550 }],
    },
    triangulation: {
      measurements: [
        { id: 'm1', start: { x: 215, y: 345 }, end: { x: 255, y: 345 }, label: 'Eye Width (Base Unit)', color: '#38bdf8', ratioToBaseUnit: 1.0 },
        { id: 'm2', start: { x: 255, y: 345 }, end: { x: 345, y: 345 }, label: 'Inter-Eye Gap', color: '#f59e0b', ratioToBaseUnit: 2.25 },
        { id: 'm3', start: { x: 300, y: 345 }, end: { x: 300, y: 440 }, label: 'Nose Height', color: '#10b981', ratioToBaseUnit: 2.37 },
      ],
      baseUnitDistance: 40,
    },
    asaro: {
      planesOpacity: 0.7,
      lightAngleDeg: 45,
    },
  },
  viewMode: 'valueStudy',
  splitPosition: 50,
  blurRadius: 0,
  isFlippedHorizontal: false,
  isolation: { kind: 'none' },
  ghostOpacity: 0.18,
  valueFamilyFloors: DEFAULT_VALUE_FAMILY_FLOORS,
  cutPointSource: 'default',
  edgeQuality: createInitialEdgeQualityState(),
  histogram: { status: 'idle' },
  landmarks: { status: 'idle' },
};
